# Ener-Stor {#Renewable-Energy-Storage}

#### Keywords {-}

Machine Learning, Renewable Energy, Fossil Fuels, Energy Storage, Clean Energy

## Maximizing utility of Renewable energy

Renewable energy generation worldwide has doubled in the last 10 years. Despite this growth, there is still a significant reliance on energy derived from conventional sources of energy. At the simplest level, this is driven by a mismatch between supply and demand. Homeowners can play a huge part in bridging this gap. While there is a growing population of consumers motivated to adopt green energy, a majority of them are standing on the sidelines due to financial considerations. Despite significant innovation in technology that has driven down the cost of home solar installations, the economics of investing in solar remain unpalatable for most consumers. Consumers are wary of long and, often, uncertain pay-back periods. 

Our solution, Ener-Stor, is a smart energy storage solution that will encourage more consumers to invest in solar energy for their homes. It combines advances in energy storage and machine learning to improve the return on investment on solar panels and significantly reduce a household’s reliance on fossil-fuel based energy. 

## Investing in smart energy storage by predicting energy wastage

Since the generation of solar energy is dependent on the amount of sunshine, there is significant volatility in energy production. At times, the supply is insufficient to meet the demand of the household (for example, at night or during overcast days) and at other times, there is more energy being generated than can be consumed. Power storage can help meet the power needs in time of short supply thus reducing (or even eliminating) the need to buy energy from the grid. When excess power is generated, it can be sold to the grid. This will result in the homeowner having a net positive income stream which can significantly improve the economics of the investment decision.

Ener-Stor is an energy storage solution that can make real-time decisions on how to optimally use the energy being produced in the home. It decides when excess energy should be sold to the grid and when it should be stored for future use by predicting future supply and demand for the household. 

Ener-Stor uses two predictive machine learning models to makes it decisions: one model to predict the hourly solar energy production and another model to predict the hourly household power demand. These models are self-learning resulting in more accurate predictions over time as they gather more data over time. 

The supply prediction is complex as solar energy production is intermittent and production depends on weather conditions such as cloud cover, sun intensity, relative humidity, and heat build up. The supply prediction model is a neural network that uses historical weather data specific to the household’s location and global satellite imagery to predict the weather conditions. It combines the weather prediction with the characteristics of the solar system installation for the household (for example, the type of materials used, the square footage of the solar panels etc.) to generate hourly supply predictions for the next 72 hours. It uses cloud computing to store and process the vast amounts of data involved.

The demand prediction model is an auto-regression model that uses historical data specific to the household’s power consumption. It uses factors like time of day, day of the week, time of the year, and also considers the trending of household power consumption over time. 
Ener-Stor will calculate the energy delta for each hour using the the predicted supply and demand for the next 72 hours. Ener-Stor will automatically route the energy being produced to the grid or to storage based on these calculations. 

## Enabling an energy secure future

The pace of climate change requires us to find innovative ways to rapidly reduce our planet’s dependence on non-renewable sources of energy. Ener-Stor can make a significant difference towards accomplishing this objective by providing a financial incentive for homeowners to invest in solar technology and become net positive contributors to the energy equation.
